AllCops:
  Exclude:
    - "google-cloud-debugger.gemspec"
    - "lib/google/devtools/**/*"
    # GAPIC client has too many violations. Exclude for now.
    - "lib/google/cloud/debugger/v2/**/*"
    - "Rakefile"
    - "test/**/*"
    - "tmp/**.*"

Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes
Style/MethodDefParentheses:
  EnforcedStyle: require_no_parentheses
Style/NumericLiterals:
  Enabled: false
Style/SpaceAroundOperators:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
Style/EmptyLines:
  Enabled: false
Style/EmptyElse:
  Enabled: false
Metrics/CyclomaticComplexity:
  Max: 10
Metrics/PerceivedComplexity:
  Max: 10
Metrics/AbcSize:
  Max: 25
Metrics/MethodLength:
  Max: 20
Metrics/ParameterLists:
  Enabled: false
Metrics/ModuleLength:
  Enabled: false
Style/RescueModifier:
  Enabled: false
Style/ClassVars:
  Enabled: false
Style/TrivialAccessors:
  Enabled: false
Style/CaseEquality:
  Enabled: false
Style/FileName:
  Enabled: false # for lib/google-cloud-debugger.rb file
